#!/bin/sh

set -e

USER="time-tracker"
PID_FILE="/var/lib/${USER}/RUNNING_PID"

sbt clean compile stage

if [ -f ${PID_FILE} ];then
  echo "[info] Stopping application (with PID `cat ${PID_FILE}`)..."
  sudo -u $USER kill `cat ${PID_FILE}`

  RESULT=$?

  if test "$RESULT" = 0; then
    echo "[info] Done!"
  else
    echo "[\033[31merror\033[0m] Failed ($RESULT)"
  fi
fi

sudo -u $USER bash -c "target/universal/stage/bin/time-tracker -XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=512M -Dconfig.file=conf/application_production.conf -Dmongodb.db="time-tracker" -Dhttp.port=12000 -Dpidfile.path=/var/lib/time-tracker/RUNNING_PID >> /var/log/time-tracker/timetracker.log&"
