#!/bin/sh

set -e

USER="time-tracker"
PID_FILE="/var/lib/${USER}/RUNNING_PID"

sbt clean compile stage

if [ -f ${PID_FILE} ];then
  echo "[info] Stopping application (with PID `cat ${PID_FILE}`)..."
  if ! $(sudo -u $USER kill `cat ${PID_FILE}`); then
    sudo rm ${PID_FILE}
  fi
fi

sudo chown $USER target/universal/stage/bin/time-tracker
sudo -u $USER bash -c "target/universal/stage/bin/time-tracker -Dconfig.file=conf/application_production.conf -Dmongodb.db="time-tracker" -Dhttp.port=12000 -Dpidfile.path=/var/lib/time-tracker/RUNNING_PID >> /var/log/time-tracker/timetracker.log&"
