version: 2
jobs:
  build_run_deploy:
    machine: true
    environment:
      SBT_VERSION_TAG: sbt-0.13.15_mongo-3.2.1_node-8.x_jdk-8
    steps:
      - checkout
      - run:
          name: prepare docker
          command: |
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            docker pull scalableminds/sbt:$SBT_VERSION_TAG
      - restore_cache:
          keys:
            - cache-{{ .Branch }}
            - cache
      - run:
          name: build webpack
          command: docker-compose run time-tracker-webpack
      - run:
          name: build sbt
          command: docker-compose run time-tracker-sbt clean compile stage
      - save_cache:
          key: cache-{{ .Branch }}
          paths:
            - "~/.m2"
            - "~/.ivy2"
            - "~/.sbt"
            - "node_modules"
      - run:
          name: build docker image
          command: |
            set -x
            sudo chown -R circleci:circleci .
            docker build -t scalableminds/time-tracker:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} .
      - run:
          name: test
          command: |
            set -x
            DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} docker-compose up -d time-tracker
            sleep 10
            ./test/infrastructure/deployment.bash
      - run:
          name: deployment
          command: |
            set -x
            docker tag scalableminds/time-tracker:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} scalableminds/time-tracker:${CIRCLE_BRANCH}
            docker push scalableminds/time-tracker:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker push scalableminds/time-tracker:${CIRCLE_BRANCH}
            docker logout

workflows:
  version: 2
  default:
    jobs:
      - build_run_deploy
