version: 2
jobs:
  build:
    machine: true
    environment:
      SBT_VERSION_TAG: sbt-0.13.15_mongo-3.2.1_node-8.x_jdk-8
    steps:
      - checkout
      - run:
          name: prepare docker
          command: |
            docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
            docker pull scalableminds/sbt:$SBT_VERSION_TAG
      - run:
          name: build webpack
          command: docker-compose run time-tracker-webpack
      - run:
          name: build sbt
          command: docker-compose run time-tracker-sbt clean compile stage
      - run:
          name: build docker image
          command: docker build --ignore-permissions -t scalableminds/time-tracker:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} .
  test:
    machine: true
    environment:
      SBT_VERSION_TAG: sbt-0.13.15_mongo-3.2.1_node-8.x_jdk-8
    steps:
      - run:
          name: test
          command: |
            set -x
            DOCKER_TAG=${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} docker-compose up -d time-tracker
            sleep 10
            ./test/infrastructure/deployment.bash
  deployment:
    machine: true
    steps:
      - run:
          name: deployment
          command: |
            set -x
            docker tag scalableminds/time-tracker:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM} scalableminds/time-tracker:${CIRCLE_BRANCH}
            docker push scalableminds/time-tracker:${CIRCLE_BRANCH}__${CIRCLE_BUILD_NUM}
            docker push scalableminds/time-tracker:${CIRCLE_BRANCH}
            docker logout

workflows:
  version: 2
  default:
    jobs:
      - build
      - test:
          requires:
            - build
      - deployment:
          requires:
            - test
