FROM scalableminds/sbt:sbt-0.13.9_mongo-3.2.1_node-4.x_jdk-8

# Install mongo tools for evolutions
RUN npm install -g bower \
 && npm install -g scalableminds/coffee-script


ENTRYPOINT [ "/bin/bash -c" ]
